# Generated by Django 4.1.5 on 2023-01-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="type",
            field=models.CharField(
                choices=[("EMPLOYEE", "Employee"), ("INTERN", "Intern")],
                default="EMPLOYEE",
                max_length=10,
            ),
        ),
    ]
