# Generated by Django 4.1.5 on 2023-01-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_management", "0002_employee_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
