# Generated by Django 4.1.5 on 2023-01-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr_management", "0003_employee_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance", unique_together={("employee", "date")},
        ),
    ]
