# Generated by Django 4.1.5 on 2023-01-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_management", "0004_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="time_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_out",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
